name: 'JSON Escape'
description: |
  JSON Escape helps to escape JSON strings by removing or encoding traces of special characters that could prevent parsing.
  It ensures correct parsing by escaping special characters, which helps to avoid errors in your application.
author: 'Pieter Joost van de Sande'

branding:
  icon: 'activity'

inputs:
  value:
    description: 'The input to escape'
    required: true

# Define your outputs here.
outputs:
  value:
    description: 'The escaped input'

runs:
  using: node20
  main: dist/index.js
